### ISSUE TITLE
Flipping the cards direction

### ISSUE THREAD

**Issue by greyboxgt** [AbduazizKayumov/Flashcard-Maker-Android#13]
This is probably an easy one. I would like to always rotate the cards clockwise when  flipping between front and back side. Perhaps, a mod in FlipAnimation.kt?

Thank you!!

**Comment by AbduazizKayumov** [comment]
Isn't working in the way you described?

**Comment by Engineerator** [comment]
It actually flips clockwise when flipping from front side to back side and counterclockwise when flipping from back side to front side. Michael asked the card to always flip clockwise.

I think I found a solution to this request. In the FlipAnimation.kt these line of code controls which way the card flips:
`if (forward)`
`degrees = -degrees //determines direction of rotation when flip begins`

Commenting these lines out flips the card left each time it is rotated. Maybe the users can be given an option to choose which direction the card flips?

**Comment by Engineerator** [comment]
It actually flips clockwise when flipping from front side to back side and counterclockwise when flipping from back side to front side. Michael asked the card to always flip clockwise.

I think I found a solution to this request. In the FlipAnimation.kt these line of code controls which way the card flips:
`if (forward)`
`degrees = -degrees //determines direction of rotation when flip begins`

Commenting these lines out flips the card left each time it is rotated. Maybe the users can be given an option to choose which direction the card flips?

Daniel.

**Comment by Engineerator** [comment]
It actually flips clockwise when flipping from front side to back side and counterclockwise when flipping from back side to front side. @greyboxgt asked the card to always flip clockwise.

I think I found a solution to this request. In the FlipAnimation.kt these line of code controls which way the card flips:

`if (forward)`
`degrees = -degrees //determines direction of rotation when flip begins`

Commenting these lines out flips the card left each time it is rotated. Maybe the users can be given an option to choose which direction the card flips?

Daniel.

**Comment by Engineerator** [comment]
It actually flips clockwise when flipping from front side to back side and counterclockwise when flipping from back side to front side. @greyboxgt asked the card to always flip clockwise.

I think I found a solution to this request. In the FlipAnimation.kt these line of code controls which way the card flips:

`if (forward)`
`degrees = -degrees //determines direction of rotation when flip begins`


Commenting these lines out flips the card clockwise each time it is rotated. Maybe the users can be given an option to choose which direction the card flips?

Daniel.

**Comment by greyboxgt** [comment]
To me the current animation feels counter-intuitive because your current icon is actually a clockwise arrow, but the card rotates clockwise and counterclockwise. Maybe having two icons - one for clockwise and another for counterclockwise rotation would be a better option?

**Comment by AbduazizKayumov** [comment]
Solved in #14

**Comment by greyboxgt** [comment]
Thank you guys for this fix! Feels much better now! Like a card, not like a book! ;-)
