### ISSUE TITLE
Networks Permission

### ISSUE THREAD

**Issue by mondstern** [AbduazizKayumov/Flashcard-Maker-Android#2]
Why does the app "Flashcard Maker" need the permission "access all networks"? I hope this permission will be removed, if not, I will never install it again.

**Comment by AbduazizKayumov** [comment]
Thank you, noted it! 
By the way, you can check all networking requests sent/received by the app, it does not send/receive anything from internet (only anonymous crash reports, which I use to fix bugs), so it should not bother 😉.
