### ISSUE TITLE
Sort and shuffle the deck set

### ISSUE THREAD

**Issue by greyboxgt** [AbduazizKayumov/Flashcard-Maker-Android#20]
When I go through my cards in forward direction, the order of the cards is the same. Quite I already remember which card will be the next and this doesn't help the learning process because the previous card should not trigger the right answer for the next unrelated card. The best way to resolve this would be to randomize/shuffle the cards like they do with the real paper cards. You already have a similar feature, but only in study mode, and to use it you would have to keep pressing the randomizing button. It would be beneficial to have the ability to shuffle the deck set "at source" and keep the change until next shuffle.

In other situations you would want to sort the deck set alphabetically and keep the change. This might be useful if you want to quickly find a certain card or duplicate cards in the big shuffled deck. In this case I would sort the deck alphabetically, find and modify the card, and then re-shuffle again.

**Comment by AbduazizKayumov** [comment]
For the second part of this issue:
1) Should I sort by the front text of a card?
2) How would you sort the cards alphabetically if some cards don't have text (they have images, drawing)?

**Comment by greyboxgt** [comment]
If there is some text, sorting should be based on the current front text.

If I want to re-sort based on the back text, I would flip using your "Reverse all cards" feature and then sort again.

If there is no text, sorting could be done based on the card contents size, similar to windows file size.

I hope this is not "easier said than done"!  :-)

**Comment by AbduazizKayumov** [comment]
I cannot look up every image file and compare their sizes (it requires me to ask FILE permissions). 
Let me sort the cards alphabetically for now and close this issue.
