### ISSUE TITLE
An option to remove an image/drawing from one side of the card

### ISSUE THREAD

**Issue by greyboxgt** [AbduazizKayumov/Flashcard-Maker-Android#23]
In the editing selection menu there is an option to add an image or drawing, but there is no option to remove an image or drawing. A user could just delete and recreate the card from scratch, but some users might want to keep the other side of the card. It would be nice if the user could remove the image or drawing directly from the Image and Drawing editing page and keep the text. In this case the menu could show "Edit text", "Add/remove image", "Add/remove drawing", "Card text color", "Card background color"

 If that is not possible, I would suggest adding "Clear the card side" menu option. This option would wipe the image/drawing and the text from just the front or the back side of the selected card depending on which side is selected and keep the information on the other side of the card.

**Comment by AbduazizKayumov** [comment]
I think "Clear the card side" is more user friendly, it avoids another bottom menu with all clearing options. Let me know if that works for you.

**Comment by greyboxgt** [comment]
If  I do "Clear the card side" when I am on the Back side of the card, only the Back side is cleared, as expected. But if  I do "Clear the card side" when I am on the Front side of the card, both - Front and Back sides are cleared instead of just the Front side.

**Comment by AbduazizKayumov** [comment]
Feel free to reopen the issue if something comes up
