### ISSUE TITLE
Flipping and saving the card side state

### ISSUE THREAD

**Issue by greyboxgt** [AbduazizKayumov/Flashcard-Maker-Android#25]
In editing module there is an option to flip a card, but it currently doesn't really save the card side state. It would be useful to have an option to flip an individual card it keep the card side state permanently in the card set.

**Comment by AbduazizKayumov** [comment]
I think flipping a card in editing module should **not** save the card side state since you are just visiting the card to make sure it has proper contents on its sides.
Wouldn't it be better to have special indicators to say "you're editing the back side" or "you're editing the front"?

**Comment by greyboxgt** [comment]
Let me explain why this could be very useful. There are situations where cards "back" and "front" sides are supposed to be mixed within one set. Especially if you are learning, you may want to have mixed backs and fronts in one set to train your brain better. For example, not just english, english, english, english, english words for the front side, but, rather english, russian, russian, english, english. This way your brain should works harder to expect to translate in both "directions" which is very good for learning. To achieve that I have to edit front and back sides manually which is much more time consuming than just flipping the card. I am sure that would be a very nice feature that will help learning. And you can always flip the card again in a simple click if you are "just visiting".

**Comment by AbduazizKayumov** [comment]
Feel free to reopen the issue if something comes up

**Comment by greyboxgt** [comment]
Works well for me!

Thank you @AbduazizKayumov  for the update and thank you @Engineerator  for making the .apk for me!

**Comment by Engineerator** [comment]
Thank you for adding this great feature!

However, I have discovered a serious issue that impacts the usability of the program. When I go to edit the back of a card, the text field that appears, shows the text on the front side of the card instead of the back side. I noticed that just before entering the text editing menu, the card flips back to the front which might be causing this issue.

**Comment by AbduazizKayumov** [comment]
Thank you for the bug report. Yes, it is a serious issue, I'll try to fix as soon as possible

**Comment by AbduazizKayumov** [comment]
The original fix involved flipping sides of a card model object [here](https://github.com/AbduazizKayumov/Flashcard-Maker-Android/blob/9e4940f6d49ec6160ac09793a7d405271d4c6fa0/app/src/main/java/com/piapps/flashcardpro/features/editor/adapter/CardsEditorAdapter.kt#L263) when user flips the card view, this commit removes "isEditingBack" boolean from the card model class. "isEditingBack" is unnecessary from now on as the editor always edits the front side. 
Feel free to reopen it if something comes up.

**Comment by Engineerator** [comment]
This commit seemed to have fixed this issue!

I have discovered another issue that is related to this issue. When flipping to the back side of an empty card, just before pressing on it to edit the text, the default string "Back side" changes to "Front side". Without changing anything and returning back to the card, the back side of the card shows the "Front side" string.

**Comment by AbduazizKayumov** [comment]
Yes, it is an expected behavior, the visible side is always "front" since we're saving the card state on each flip. Let's remove the words, "front" and "back", and use the word "side" as a default side text.

**Comment by AbduazizKayumov** [comment]
Let me know if there is any other word that we can use for default text on card sides.

**Comment by Engineerator** [comment]
This might be a minor cosmetic issue, but I think that we should change the default side text to "Text" because it doesn't sound right to say that a card has two front sides.

**Comment by greyboxgt** [comment]
It is very nice that we have the "Shuffle cards" feature. I think it would also be useful to introduce the "Shuffle card sides" feature when the card number in the set does not change, but only the sides of the cards in the set are randomly changed. The result will be similar to https://github.com/azizkayumov/Flashcard-Maker-Android/issues/25#issuecomment-699542857, but automatic instead of manual. And we can always use the "Shuffle Cards" command separately in addition to the "Shuffle card sides" if we want.

**Comment by azizkayumov** [comment]
Published a new release on Google Play, let me know if something comes up
