### ISSUE TITLE
Sorting cards alphabetically with mixed case

### ISSUE THREAD

**Issue by greyboxgt** [AbduazizKayumov/Flashcard-Maker-Android#26]
I noticed the cards sorting alphabetically doesn't work as expected. For example, if I have 6 cards with the front side text that start with different mixed case letters:

`B, C, A, c, a, b`

I would expect the 6 alphabetically sorted cards to be in this order:

`A, a, B, b, C, c`

i.e. upper case letter, then same letter lower case, then the next alphabet letter upper case and same letter lower case sequence.

But the application sorts the cards like this:

`A, B, C, a, b, c`

i.e. upper case cards alphabetically, then lower case cards alphabetically

**Comment by AbduazizKayumov** [comment]
I could not sort it in this order:
`A, a, B, b, C, c`
The one I pushed converts all front texts to lowercase and sorts, so it may produce this order (depending on the prev. order):
`a, A, B, b, C, c`, sometimes even different: `A, a, b, B, C, c`. 
Let me know if that works for you.
I could not find any "built-in" sort function to do this, if the order is not desirable, then I would try to implement a custom sort to force this order: `A, a, B, b, C, c`

**Comment by greyboxgt** [comment]
A, a, B, b, C, c seems to be the default for Microsoft Word and Excel sorting. 
But I think just ignoring the case is also a good option.  Thank you for the fix!

I will ask Daniel to make an apk for me to try. 
I wonder why you are not updating the application in Google Play Store?

**Comment by AbduazizKayumov** [comment]
Yes, I will update the app on Play Store once all remaining issues are closed.
