### ISSUE TITLE
Drag & drop to change set order

### ISSUE THREAD

**Issue by greyboxgt** [AbduazizKayumov/Flashcard-Maker-Android#27]
There is currently no way to change the default view of the card sets selection page. The card set icons appear in the order they were created. In the example below I would like to move January set icon to be the first icon on the top of the page and December to the bottom to be the last one, but I cannot do it. Would it be possible to drag the card sets icons by Tap & Hold + Drag gesture?

![Screenshot_2020-10-10-12-28-49](https://user-images.githubusercontent.com/11550307/95663813-0d397000-0af7-11eb-80f4-7deaa264856d.png)

**Comment by AbduazizKayumov** [comment]
Todo:

- [ ] Bug on the item added animation for newly created sets
- [ ] Remove the blinking animation on each item update
- [ ] How to reorder sets for specific labels?

**Comment by AbduazizKayumov** [comment]
I released the beta version just now, it should be live in few hours. 
The drag & drop animation seems little bit strange at first, you may find it hard to put a set to the first position in a grid -> just hold any set -> drag up until you reach the top of everything -> drop it in the cleared area. Any scroll may cause the list to animate the reorder operation, it is messy somehow. Let me know if something comes up.

**Comment by greyboxgt** [comment]
I think the reordering works very well, thank you very much!!

**Comment by AbduazizKayumov** [comment]
The previous beta could lead to new bugs: if one reorders sets in "All sets" section, opens "X" label section and reorders there, all "X" labelled sets are placed on top in "All sets" section. 
The last commit adds the ability to reorder sets for each label. For example, if you reorder sets labelled with "X" in the "All sets" section, you can now open "X" label section and reorder there too, and the reordering operation will be effective in the "All sets" section. I was thinking, users may want to reorder sets with some label specifically, so the synchronization between all sets should now work perfectly.
The new beta version will reorder your sets according to their creation date (using set IDs as order numbers).
