### ISSUE TITLE
Icons consistency in different modules

### ISSUE THREAD

**Issue by greyboxgt** [AbduazizKayumov/Flashcard-Maker-Android#28]
I noticed that the same function icons in different modules are not always consistent. For example, to exit from the editing module we use the "back arrow" ← icon, but to exit from study and exam we use the "X" icon. But "X" in editing module deletes the card for good! Back arrow ←  is also used to select the previous card. I would suggest to use the "less than" "<" icon to exit from any module:

![editing module-s](https://user-images.githubusercontent.com/11550307/96020851-812f8d00-0e03-11eb-9ae5-a422f900bc68.jpg)

__________________________________________________________________________________________________________________________________
Study module would look like this:

![study module-s](https://user-images.githubusercontent.com/11550307/96020883-8c82b880-0e03-11eb-8afd-268e1421eb37.jpg)

__________________________________________________________________________________________________________________________________

In study module all the icons are consistent with the editing module. But in exam module the red "eye" and green "check" icons are too distracting. I would suggest the "rotation" icon on the right side and "check" icon on the left side similar to editing module for consistency, so exam module would look like this:

![exam module-s2](https://user-images.githubusercontent.com/11550307/96308524-69e5d080-0fb8-11eb-9bce-b26bc4c48696.jpg)

__________________________________________________________________________________________________________________________________

On the main screen the new set creation icon is currently white "plus" in red circle. I would suggest  the grey "plus" in white fill circle and dark grey stroke or some shadow to be consistent with editing module "add a new card" icon:

![main module](https://user-images.githubusercontent.com/11550307/96020954-a2907900-0e03-11eb-960b-b76ae72bef70.jpg)

**Comment by AbduazizKayumov** [comment]
Thank you for feedback.

I think "←" should stay the same as it is since the official design guidelines show that "←" icon is used for [Appbars](https://material.io/components/app-bars-top). Study & Quiz modules should use the "←" icon too (pushing the change below). Let's change the "next" and "previous" icons to "<", ">" to make it different from "exiting". 

Regarding to the floating action buttons (circle buttons), I would be happy to follow the [official guidelines](https://material.io/components/buttons-floating-action-button). As far as I understand from the guidelines, the floating action buttons should represent the primary actions of a screen: marking the card as "Yes, I know" or "No, I don't remember" in Quiz module and "Create a new set" on the Main screen. I don't think a light circle button with dark border follows the Material design as it has 3 elements: surface+border+icon, while it would be a combination of just 2 elements: surface+icon.

**Comment by greyboxgt** [comment]
Thank you for fixing the "back" icon!


The standard Google rainbow "plus" on white background icon seems to have the shadow to make enough contrast even with white card set. And the rainbow "plus" could reflect the fact that your newly created card set has a random initial color:

![white button](https://user-images.githubusercontent.com/11550307/96508913-22f21800-1210-11eb-9b23-0ddca9401994.jpg)
-----------------
I still think that current green/red/  Yes/No buttons are too bright and distracting for the exam. Maybe neutral colors happy/sad smileys will be agree with the guidelines?

![exam module-s2](https://user-images.githubusercontent.com/11550307/96509288-a27fe700-1210-11eb-80a9-a51c894f3380.jpg)

**Comment by AbduazizKayumov** [comment]
Removed the distracting buttons from Quiz module and replaced them with simple "flip" and "check" buttons, feel free to reopen the issue if something can be improved further:

![device-2020-10-26-120517](https://user-images.githubusercontent.com/14273342/97130076-bd5bd980-1783-11eb-9f28-160aa2cf8869.png)

**Comment by AbduazizKayumov** [comment]
I noticed that you create flashcards with sentences (not just words on each side), I think sentences are more efficient and worth remembering than just words. Usually, I create flashcards with just words, so I always have a hard time finding an appropriate word when I speak or want to explain something. I would love to hear your experience how to use the app more efficiently.

**Comment by greyboxgt** [comment]
Thank you very much for fixing this!

I use everything: words, phrasal verbs, sentences, especially idioms. From my experience, the set should be 20 cards maximum. I often shuffle the cards (thank you for this feature!) After some cards are learned, I move them to an temporary (monthly) archive (thank you for this wonderful feature!), and add new cards. About a month later I load that archived set and delete the cards I think I learned. If I have a problem with some cards, I move them back to current set.

One thing I can tell you this application became a part of my life. I hope you will be able to share your Flash Card Maker with other people, so they can benefit from it. A few feature requests are still outstanding. The most important to me would be Excel import-export (#9) and Drag & drop to change set order (#27).

**Comment by AbduazizKayumov** [comment]
Thank you for sharing your experience, I need to definitely remake my flashcards, I have about 50 flashcards on average, so my sets are really challenging to learn, 20 flashcards would be a perfect frequency.
So happy to hear that you find the app helpful. 
I usually contribute to the app in weekends, I hope I will be able to push the feature requests soon.
