### ISSUE TITLE
Default card settings

### ISSUE THREAD

**Issue by AbduazizKayumov** [AbduazizKayumov/Flashcard-Maker-Android#32]
Users should be able to set default colors and text size for newly created sets (instead of random selection):

- [x] Set default card background color

- [x] Set default card text color

- [x] Set default card text size

**Comment by greyboxgt** [comment]
To simplify the interface, you could always start with black on white size 28 and let the user decide. 
Or black on white size 28 to start and then memorize the user latest modification and make that the default for the next new card set.

**Comment by greyboxgt** [comment]
To simplify the interface, you could always start with black on white size 28 and let the user decide how to change.
Or black on white size 28 to start and then memorize the user latest modification and make that the default for the next new card set.

**Comment by greyboxgt** [comment]
To simplify the interface, you could always start with black on white size 28 and let the user decide how to change.
Or start with black on white size 28 and then memorize the user latest modification and make that to be the default for the next new card set.

**Comment by AbduazizKayumov** [comment]
I was thinking about a special settings interface with default card on it, where users can edit the default card settings. As you said, just saving the last settings would be more suitable and simpler.

**Comment by greyboxgt** [comment]
Works as described, thank you!!
