### ISSUE TITLE
The card font size

### ISSUE THREAD

**Issue by greyboxgt** [AbduazizKayumov/Flashcard-Maker-Android#7]
The font size is too big for some words. Users should be able to pick up and configure the font they want by a pinching motion and/or by pressing +/- icons. As a quick workaround @Engineerator  suggested changing textSize from 32F to 28F, but it would be nice to give users a chance to set the font size they want.

**Comment by AbduazizKayumov** [comment]
This commit adds a font size editor for card front and back texts.
The editor sets the font size for a card side that is visible, so two card sides' font sizes must be set separately:
![device-2020-09-26-145151](https://user-images.githubusercontent.com/14273342/94331628-19a6ce80-0009-11eb-9b7b-014267d05e63.png)
Let me know if that works for you.

**Comment by AbduazizKayumov** [comment]
I think it would be nice to have an option to change all cards' font sizes.

**Comment by AbduazizKayumov** [comment]
I think the last commit can close the issue, feel free to reopen it if something comes up.
![device-2020-09-26-153441](https://user-images.githubusercontent.com/14273342/94332222-224dd380-000e-11eb-9826-f1a2cef47b2d.png)

**Comment by greyboxgt** [comment]
Works very well, thank you very much for adding this feature!!!

**Comment by greyboxgt** [comment]
Would it be possible to add pinch-zoom gesture to change the font size in addition to "Set the card font size" menu option?

**Comment by AbduazizKayumov** [comment]
That's a good idea! In terms of user experience, how would you imagine setting the font size **for all cards** after pinch-zoom gesture?

**Comment by greyboxgt** [comment]
I think the same font size for all cards in the deck will work very well. And it will probably be easier to implement.

**Comment by greyboxgt** [comment]
If you are going to implement the pinch-zoom gesture feature, you may want to re-open this issue.

**Comment by AbduazizKayumov** [comment]
Indeed, that would be a great enhancement. By the pinch-zoom gesture, how should we ask the user whether he wants to set the new font size to all cards or to a single card he's pinch-zooming? Like should I display a dialog with "Would you like to set the new font size to all cards?" right after the pinch-zoom gesture?

**Comment by greyboxgt** [comment]
I still think that same font size for all cards within the card set will work very well and it will probably be easier to implement. And you already used the same approach for the card set colors.

**Comment by AbduazizKayumov** [comment]
The last commit adds the pinch-zoom gesture to change the card text size. The changes must be visible in a few hours in Open testing. Let me know if that works for you.

**Comment by greyboxgt** [comment]
Works very well, thank you very much!!
