### ISSUE TITLE
Font type and background colors

### ISSUE THREAD

**Issue by greyboxgt** [AbduazizKayumov/Flashcard-Maker-Android#8]
Is it possible to add more font background colors? My favorite would be orange font on black background.

It would also be nice to give users a chance to change the font type. Some fonts like Sans Forgetica are designed using the principles of cognitive psychology to help you to better remember your cards.

**Comment by AbduazizKayumov** [comment]
@greyboxgt SansForgetica website states [that](https://sansforgetica.rmit/):
> Sans Forgetica is designed for non-commercial use only. It is bound by a creative commons, non-commercial, attributed (CCBYNC) license.

So can I use it since this app is open-source and non-commercial (free & ad-free)?
Here I tried to use the font in Study module:
![device-2020-04-11-175556](https://user-images.githubusercontent.com/14273342/79039587-267f6380-7c1d-11ea-9948-57978dafb014.png)

**Comment by AbduazizKayumov** [comment]
Unfortunately, SansForgetica does not work on Cyrillic words, the font design contains only latin letters:
<img width="388" alt="Screen Shot 2020-04-11 at 18 16 48" src="https://user-images.githubusercontent.com/14273342/79039974-0309e800-7c20-11ea-9c96-13d28d71cd29.png">

**Comment by greyboxgt** [comment]
I didn't know, sorry. I only heard this font helps to memorize text. Do you know it it would be legal for me or somebody else to modify the original font and add the missing characters?

With your initial approach, can a user select ANY font, or the font has to be hard coded? 

And for the colors, I looked at your older Flashcard application and there was an option to select any HEX color. Maybe you could re-introduce this option?

**Comment by AbduazizKayumov** [comment]
Nope, one cannot select ANY font, I just downloaded the font and tried it, you guys may want to try it as well, it is on a separate branch:
https://github.com/AbduazizKayumov/Flashcard-Maker-Android/tree/forgetica

Yes, I will add the color wheel in the next commits.

**Comment by Engineerator** [comment]
Would it be possible if you could provide the source code from the older version of the program? I may be able to assist in re-introducing the color wheel and maybe some other features.

**Comment by greyboxgt** [comment]
Yes, the color wheels for the font and the background would be a very nice feature!

**Comment by AbduazizKayumov** [comment]
The last commit removes default colors and adds color wheel for any color picker (set color, card background or card text color). I ended up using this [library](https://github.com/QuadFlask/colorpicker):
![device-2020-10-05-001511](https://user-images.githubusercontent.com/14273342/95019372-f67ebd80-069f-11eb-9f2d-59f766f4f68c.png)
Let me know if anything could be improved.

**Comment by greyboxgt** [comment]
The color wheel is a very nice addition, thank you very much for this fantastic feature!!!

I have a few notes/suggestions:

1. When changing the card text color we cannot always see the actual text on the screen because the color wheel window is most of time bigger than the text on the screen behind it. And also with many background colors the default icons color doesn't show enough contrast. But because we can always see the "pencil" and the "X" icons on the top, we can also use the same color attribute for the text and for all four corner icons to see the result immediately while picking up the text color. This should resolve the problems I just mentioned and should also look much better that way.

2. You currently have color wheels for the font and the background of the individual cards, but the color wheel for the card set is designed only for the background. And if we set the new card set background color, it overwrites the previously defined individual cards text and background colors. To resolve this and simplify the process similar to what you are going to do to the font size, we could to get rid of individual card colors and use the same text and background colors for the entire card set. You would need to add the <ins>A</ins> color wheel icon to set the card set text.

**Comment by AbduazizKayumov** [comment]
Thank you for your feedback. Yes, I think the same text and background colors for all set cards would be a reasonable choice for everyone.
The last commit fixes the 2 issues you mentioned above. 
Let me know if that works for you.

**Comment by greyboxgt** [comment]
Works great and looks very nice, thank you very much for the update!

![Screenshot_2020-10-10-12-22-57](https://user-images.githubusercontent.com/11550307/95663553-f85bdd00-0af4-11eb-9788-98d0123d0b39.png)
